--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/BlockLagFix
build-by-default: true
branches:
- master
projects:
  BlockLagFix:
    path: ""
    icon: icon.gif
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.3
...
